# Generated by Django 3.2.7 on 2021-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkasse', '0002_alter_account_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='comment',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
