# Generated by Django 3.2.7 on 2021-09-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barkasse', '0003_auto_20210930_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.TextField(null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Konto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barkasse.account', verbose_name='Konto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Bezeichnung'),
        ),
    ]
