# Generated by Django 3.2.7 on 2021-10-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barkasse', '0005_account_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barkasse.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barkasse.household')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='accounts',
            field=models.ManyToManyField(through='barkasse.HouseholdAccount', to='barkasse.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='households',
            field=models.ManyToManyField(through='barkasse.HouseholdAccount', to='barkasse.Household'),
        ),
    ]
