# Generated by Django 3.2.7 on 2021-10-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barkasse', '0006_auto_20211001_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='households',
        ),
        migrations.RemoveField(
            model_name='household',
            name='accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barkasse.household'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barkasse.household'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barkasse.household'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HouseholdAccount',
        ),
        migrations.AddField(
            model_name='member',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barkasse.household'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
