# Generated by Django 3.2.7 on 2021-10-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barkasse', '0007_auto_20211001_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
    ]
