# Generated by Django 3.2.7 on 2021-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkasse', '0008_remove_account_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bezeichnung'),
        ),
    ]
