# Generated by Django 3.2.7 on 2021-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkasse', '0009_auto_20211004_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kontonummer'),
        ),
    ]
